services:
  app:
    build:
      context: .
      target: dev
    restart: always
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "8888:80"
    volumes:
      - ./public:/app/public
      - ./src:/app/src
